src/Pages/Cart.cshtml.cs
using System.Threading.Tasks;
using src.Core.Domain.Cart;
using src.Core.Domain.Cart.Pipelines;
using src.Helpers;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;

namespace src.Pages;

public class CartModel : PageModel
{
    private readonly IMediator _mediator;
    public string[] Errors { get; private set; } = System.Array.Empty<string>();
    public CartModel(IMediator mediator) => _mediator = mediator ?? throw new System.ArgumentNullException(nameof(mediator));

    [BindProperty]
    public string customerName { get; set; } = null!;
    [BindProperty]
    public string building { get; set; } = null!;
    [BindProperty]
    public string roomNumber { get; set; } = null!;
    [BindProperty]
    public string notes { get; set; } = null!;

    public ShoppingCart? Cart { get; private set; }

    public async Task OnGetAsync()
    {
        var cartId = HttpContext.Session.GetGuid("CartId");
        if (cartId is null) return;

        Cart = await _mediator.Send(new Get.Request(cartId.Value));
    }

    public async Task<IActionResult> OnPostAsync()
    {
        var cartId = HttpContext.Session.GetGuid("CartId");
        if (cartId is null) return RedirectToPage("/Index");
        Cart = await _mediator.Send(new Get.Request(cartId.Value));

        var result = await _mediator.Send(new CartCheckout.Request(cartId.Value, customerName, building, roomNumber, notes));
        if (result.Success)
        {
            HttpContext.Session.Remove("CartId");
            return RedirectToPage("/Orders/OrderDetails", new { id = result.OrderId });
        }
        Errors = result.Errors;
        return Page();
    }
}

src/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace src.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
	public string RequestId { get; set; } = "";

	public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

	private readonly ILogger<ErrorModel> _logger;

	public ErrorModel(ILogger<ErrorModel> logger)
	{
		_logger = logger;
	}

	public void OnGet()
	{
		RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
	}
}

src/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using src.Core.Domain.Products;
using src.Helpers;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace src.Pages;

public class IndexModel : PageModel
{
    private readonly IMediator _mediator;
    public IndexModel(IMediator mediator) => _mediator = mediator;

    public List<FoodItem> FoodItems { get; set; } = new();

    public async Task OnGetAsync()
        => FoodItems = await _mediator.Send(new Core.Domain.Products.Pipelines.Get.Request());

    public async Task<IActionResult> OnPostAddToCartAsync(int id, string name, decimal price)
    {
        var cartId = HttpContext.Session.GetGuid("CartId");
        if (cartId == null)
        {
            cartId = Guid.NewGuid();
            HttpContext.Session.SetString("CartId", cartId.ToString());
        }

        await _mediator.Send(new Core.Domain.Cart.Pipelines.AddItem.Request(id, name, price, cartId.Value));

        return RedirectToPage();
    }
}

src/Pages/Cart.cshtml
@page
@model src.Pages.CartModel
@{
	ViewData["Title"] = "Shopping cart";
}

<div class="text-center mt-4">

	<h1 class="display-4 mt-5">Your cart</h1>
	<div class="text-left">
		@if (Model.Cart is null)
		{
			<p>There is nothing in your cart</p>
		}
		else
		{
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Dish</th>
						<th scope="col">Count</th>
						<th scope="col">Price</th>
						<th scope="col">Sum</th>
					</tr>
				</thead>
				<tbody>

					@foreach (var item in Model.Cart.Items)
					{
						<tr>
							<th scope="row">@item.Name</th>
							<td>@item.Count</td>
							<td>@item.Price</td>
							<td>@item.Sum</td>
						</tr>
					}
				</tbody>
			</table>
		}

		<form method="post">
			<input type="text" asp-for="customerName" placeholder="Name" />
			<input type="text" asp-for="building" placeholder="Buidling" />
			<input type="text" asp-for="roomNumber" placeholder="Room number" />
			<input type="text" asp-for="notes" placeholder="Notes" />
			<button type="submit" class="btn btn-primary">Checkout</button>
			@foreach (var error in Model.Errors)
			{
				<p class="text-danger">@error</p>
			}
		</form>
	</div>
</div>

src/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<form method="post">
<div class="text-center">
    <h1 class="display-4 mt-5">Menu</h1>

    @for (int index = 1; index <= 3; index++)
{
    <div class="menu">
            <img src="~/img/Menu0@(index).png" />

            <ul>
                @foreach (var item in Model.FoodItems.Skip((index - 1) * 8).Take(8))
            {

                <li>
                        <div class="header">
                            <h2>@item.Name</h2>
                            <p class="price">Kr @string.Format("{0:#0.00}",item.Price)</p>
                        </div>
                        <div class="body">
                            <div>

                                <p class="text">@item.Description</p>
                                <p class="cooking-time">@item.CookTime min</p>
                            </div>
                            <button type="submit" asp-page-handler="AddToCart"
                                asp-route-id="@item.Id"
                                asp-route-name="@item.Name"
                                asp-route-price="@item.Price.ToString("0..00")"
                                  ><img src="~/img/addToCart.svg" height="20" width="20">
                            </button>
                            
                        </div>
                    </li>
            }
            </ul>
        </div>
}


</div>
</form>